spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.2:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000